version: "3.3"
services:

    web-app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        env_file:
            - .env
        environment:
            - DB_HOST=postgres_db
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}

        command: >
            sh -c "python main.py"

        depends_on:
            postgres_db:
                condition: service_started
        restart: always


    postgres_db:
        container_name: postgres_db
        image: postgres:15.1-alpine
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
            interval: 5s
            timeout: 5s
            retries: 5
        ports:
            - "5432:5432"
