services:

    database:
        container_name: postgres_db
        image: postgres:14.6-alpine
        restart: always
        environment:
            - POSTGRES_DB=dbname
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=password
        ports:
          - "5432:5432"